---
driver:
  name: vagrant

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

provisioner:
  name: salt_solo
  formula: i3wm
  salt_copy_filter:
    - .git
    - .kitchen
  pillars-from-files:
    i3wm.sls: pillar.example.sls
  pillars:
    top.sls:
      base:
        '*':
          - i3wm
  state_top:
    base:
      '*':
        - i3wm

suites:
  - name: default
